### ISSUE TITLE
How to implement From<Option<T>> for Value where T is my custom value?

### ISSUE THREAD

**Issue by nappa85** [SeaQL/sea-orm#107]
Let's say I have a field in my table, something like
```sql
status: CHAR(1) NOT NULL
```
status can have those values: A (active), D (deleted), Q (queued), E (executed).
I want to map the field to a Rust enum, I can easily do:
```rust
pub enum Status {
  Active,
  Deleted,
  Queued,
  Executed,
}

impl From<Status> for Value {
  fn from(s: Status) -> Value {
    Value::from(match s {
      Status::Active => "A",
      Status::Deleted => "D",
      Status::Queued => "Q",
      Status::Executed => "E",
    })
  }
}
```
and everything works fine.

But if my status is, instead
```sql
status: CHAR(1) DEFAULT NULL
```
In my Model I would have to use Option< Status>, and I cant impl From< Option< Status>> for Value, because neither Option or Value comes from my crate.

Maybe you could solve removing every impl From< Option< Something>> for Value and replacing it with a simple impl< T: Into<  Value>> From< Option< T>> for Value, I don't know if there would be conflicts, but this way you unlock a lot of custom types potentials

**Comment by tyt2y3** [comment]
They're defined in https://github.com/SeaQL/sea-query/blob/cfae4eab32fcd1a87103cffcf8760315f404656f/src/value.rs#L173
So you think
```rust
 impl< T: Into< Value>> From< Option< T>>
```

would help?

**Comment by nappa85** [comment]
Yes, I've gone there only after opening the issue, and saw how you implemented Value...
This way you're locked by type, because for example bool values goes into Value::Bool and I can't see a generic to reconduce a None::<T> into the righ Value variant.
A solution could be introduce Value::Null, this way the null value would be unique instead of typed.

To be honest, the same approach has been used by, for example, by serde_json::Value, where variants aren't Option, and there is a Null variant to express the null value without knowing the type of the field.

I don't know if your approach has been forced by some requirements, but it's kind of less flexible.
How do you see it?

**Comment by tyt2y3** [comment]
It was only recently being removed https://github.com/SeaQL/sea-query/pull/107
________________________________
寄件者: Marco Napetti ***@***.***>
寄件日期: Thursday, August 26, 2021 12:20:07 AM
收件者: SeaQL/sea-orm ***@***.***>
副本: Chris Tsang ***@***.***>; Comment ***@***.***>
主旨: Re: [SeaQL/sea-orm] How to implement From<Option<T>> for Value where T is my custom value? (#107)


Yes, I've gone there only after opening the issue, and saw how you implemented Value...
This way you're locked by type, because for example bool values goes into Value::Bool and I can't see a generic to reconduce a None:: into the righ Value variant.
A solution could be introduce Value::Null, this way the null value would be unique instead of typed.

To be honest, the same approach has been used by, for example, by serde_json::Value, where variants aren't Option, and there is a Null variant to express the null value without knowing the type of the field.

I don't know if your approach has been forced by some requirements, but it's kind of less flexible.
How do you see it?

**Comment by nappa85** [comment]
I see...
Well, this is a problem...
A solution could be a Trait that adds a method like `fn null() -> Value`
that returns the correct variant of Value containing None, and requiring
that trait in the generic impl

Il mer 25 ago 2021, 18:42 Chris Tsang ***@***.***> ha scritto:

**Comment by tyt2y3** [comment]
With #108 merged, is there still any other blocker?

**Comment by nappa85** [comment]
No, on this topic there are no blockers
