### ISSUE TITLE
sea-orm-cli generate entity command does not generate entity mapping from the database

### ISSUE THREAD

**Issue by perillamint** [SeaQL/sea-orm#1250]
## Description

`sea-orm-cli generate entity` does not generate entities from database

## Steps to Reproduce

1. Run `cargo install --version 0.10.4 sea-orm-cli`
2. set `DATABASE_URL` to point the database
3. run `sea-orm-cli generate entity -v -o src/entity --with-serde both`

### Expected Behavior

`sea-orm-cli` generates entity mappings from the database

### Actual Behavior

`sea-orm-cli` does not generate any entity mapping

### Reproduces How Often

Always

## Versions

sea-orm-cli 0.10.4
PostgreSQL 14.3
Tested on Mac OS X and Linux (Fedora 36)

## Additional Information

None

**Comment by pmnxis** [comment]
Add some extra information about the story.
We were working with `0.10.1`, before 1 hours ago (2 hours ago, `0.10.4` was updated), I updated new `sea-orm-cli`.
Suddenly sea-orm-cli generating was not working.
After then we downgraded & tested `0.10.2` and `3` and those are working great.

Also upgrade `sea-orm` to `0.10.4`, but `sea-orm-cli` `0.10.4` wasn't generate entities.
Argue carefully, I think the cause of this issue would be discovered quickly because it can cause confusion to users who newly install `0.10.4`.

**Comment by edg-l** [comment]
It doesn't generate entities for me either, only the mod.rs and prelude.rs with nothing on the prelude.rs

**Comment by billy1624** [comment]
Hey everyone, I just yanked sea-orm-cli 0.10.4 and working on the fix. Thanks everyone for the prompt report!

**Comment by billy1624** [comment]
Sorry for the inconvenience caused. I just released `sea-orm-cli` 0.10.5

I also file a issue to improve the testing of CLI module to prevent it from happening again.
