### ISSUE TITLE
u64 unsupported by sqlx-sqlite

### ISSUE THREAD

**Issue by dob9601** [SeaQL/sea-orm#1400]
## Description
Using a u64 in the field of a database model yields the error `u64 unsupported by sqlx-sqlite` when used with the sqlite backend, even though [the docs](https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type) seems to suggest that u64's are supported.

## Steps to Reproduce

Use a database model containing a u64 with a sqlite-based backend.
1. 
2. 
3. 

### Expected Behavior

Either no error to occur - or more likely, the docs to reflect the fact that u64s aren't supported in sqlite (see: https://github.com/launchbadge/sqlx/issues/2284#issuecomment-1376840943)

### Actual Behavior

`panicked at 'u64 unsupported by sqlx-sqlite'`

### Reproduces How Often

Reproducible 100% of the time

## Versions

```
├── sea-orm v0.10.6
│   ├── sea-orm-macros v0.10.6 (proc-macro)
│   ├── sea-query v0.27.2
│   │   ├── sea-query-derive v0.2.0 (proc-macro)
│   ├── sea-query-binder v0.2.2
│   │   ├── sea-query v0.27.2 (*)
│   ├── sea-strum v0.23.0
│   │   └── sea-strum_macros v0.23.0 (proc-macro)
│   ├── sea-orm v0.10.6 (*)
├── sea-orm v0.10.6 (*)
```

**Comment by dob9601** [comment]
Possible workaround might be to store u64s as a BLOB in sqlite

**Comment by JoelTorresAr** [comment]
I have the same case with sea-orm migration and mysql. big_unsigned and unsigned have the same size u32

**Comment by tyt2y3** [comment]
We might want to backport https://github.com/SeaQL/sea-query/pull/556 to sea-query 0.28

**Comment by billy1624** [comment]
SQLx's SQLite driver doesn't support `u64`. We have two options:

1. Update [the docs](https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type) and specify `u64` isn't supported in SQLite

2. Encode & decode `u64` as `u32`. Encoding side (similar to this but `TryInto<u32>`): https://github.com/SeaQL/sea-query/blob/7c4e4094252ead1b7db39cec64db7ed82d1e7fab/sea-query-binder/src/sqlx_sqlite.rs#L34-L36.

**Comment by billy1624** [comment]
As a temporary "fix" before a consensus has been reached, I'm going to update the docs.
- https://github.com/SeaQL/seaql.github.io/pull/88

**Comment by matdexir** [comment]
Hi @billy1624, I would like to know give the second option a shot. But I am afraid that I may need some hand holding to properly fix it
I have a few questions:
1. Should changing the section you mentioned be enough?
2. Do I need to add any testing? If yes, should it be inside sea-query or sea-orm?

**Comment by billy1624** [comment]
Hey @matdexir, sorry for the misinformation.

> Encode & decode `u64` as `u32`

This isn't ideal. A better option would be "encode & decode `u64` as `i64`". Since the encoding part already handled by SeaQuery. No changes is necessary.

> 1. Should changing the section you mentioned be enough?

We only need to change the decoding logics in SeaORM. Which is located at:

https://github.com/SeaQL/sea-orm/blob/d8a2428f460a50ad851db01718976267364a4a3d/src/executor/query.rs#L331-L335

So, we want to get an `Option<i64>` from the query result then cast it into `u64`.

Similar to this code snippet:

https://github.com/SeaQL/sea-orm/blob/d8a2428f460a50ad851db01718976267364a4a3d/src/executor/query.rs#L455-L470

> 2. Do I need to add any testing? If yes, should it be inside sea-query or sea-orm?

A test case on SeaORM side would be perfect. Where we try saving and select a model with an `u64` field.

**Comment by matdexir** [comment]
> This isn't ideal. A better option would be "encode & decode u64 as i64". Since the encoding part already handled by SeaQuery. No changes is necessary.

Basically what I was thinking as well, since the former solution would result in memory/value loss. I know that we also lose out almost on about half of the values present in u64 by using i64 but the use cases for such big numbers are quite rare.

Regarding the implementation, I was wondering, should I introduce a new block of with a structure similar for u32/f64
i,e: 
https://github.com/SeaQL/sea-orm/blob/d8a2428f460a50ad851db01718976267364a4a3d/src/executor/query.rs#L486-L528

But instead more like this:
```rust
impl TryGetable for u64
```

However I think that this may be too overkill.
Or maybe something closer to this?
https://github.com/SeaQL/sea-orm/blob/d8a2428f460a50ad851db01718976267364a4a3d/src/executor/query.rs#L138-L146
Which would look like:
```rust
impl TryGetable for Option<i64>
```
What do you think?

Very Thankful for your assistance~~

**Comment by tyt2y3** [comment]
`u64 unsupported by sqlx-sqlite` is a pretty inherit limitation that we are not able to work around.
