### ISSUE TITLE
Connection Pool retry option

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#1523]
Right now, the behaviour is to throw an Error when SeaORM cannot acquire a connection from the pool. We can add an option, with a timeout, on the `ConnectOptions`: `set_retry_on_pool_full` (or a better name). So that when the pool is fully-utilized, we can optionally `await` for the said period and retry before throwing an error.

**Comment by fMeow** [comment]
Also, the Error thrown does not contains additional informantion for the failed reason. The user cannot tails from the error whether it's caused by a closed connection pool or a full pool. 

The inner `sqlx` backend actually returns an Error which shows the underlying reason that fails the acquire aciton. See [`sqlx::Pool::acquire`](https://docs.rs/sqlx/0.6.2/sqlx/struct.Pool.html#method.acquire). And `sea-orm` only returns an ambiguous `ConnectionAcquire`. This is true for all [`mysql`](https://github.com/SeaQL/sea-orm/blob/8345dd5c28de3316d3e0a9c0f16d3ef2383529a3/src/driver/sqlx_mysql.rs#L93), [`postgres`](https://github.com/SeaQL/sea-orm/blob/8345dd5c28de3316d3e0a9c0f16d3ef2383529a3/src/driver/sqlx_postgres.rs#L108) and [`sqlite`](https://github.com/SeaQL/sea-orm/blob/8345dd5c28de3316d3e0a9c0f16d3ef2383529a3/src/driver/sqlx_sqlite.rs#L100) driver, for all provided operations like `execute`, `query` and etc.

**Comment by conmulligan** [comment]
This would be very helpful. As it stands, it's very difficult to debug `ConnectionAcquire` errors without being able to inspect the underlying error.

**Comment by billy1624** [comment]
Seems that SQLx will retry the `acquire` ([source code](https://github.com/launchbadge/sqlx/blob/4f1ac1d6060ee73edf83c8365fafb12df44deecc/sqlx-core/src/pool/inner.rs#L239-L290)) operation

**Comment by billy1624** [comment]
Providing clear "failed to acquire" error message is another topic of concern but I do think @fMeow and @conmulligan made a good point. We should provide the underlying error where available.

**Comment by tyt2y3** [comment]
We can extend `ConnectionAcquire` into `ConnectionAcquire(FailedToAcquireReason)`

**Comment by tyt2y3** [comment]
> Seems that SQLx will retry the `acquire` ([source code](https://github.com/launchbadge/sqlx/blob/4f1ac1d6060ee73edf83c8365fafb12df44deecc/sqlx-core/src/pool/inner.rs#L239-L290)) operation

May be I am wrong, but I don't think it has a semantics of "retry until succeed".

**Comment by billy1624** [comment]
I think SQLx has it already. One can set a connection acquire timeout.
```rs
let base_url = std::env::var("DATABASE_URL").unwrap();
let mut opt = sea_orm::ConnectOptions::new(format!("{base_url}/connection_ping_closed"));
opt
    // The connection pool has a single connection only
    .max_connections(1)
    // A controlled connection acquire timeout
    .acquire_timeout(std::time::Duration::from_secs(2));
```
https://github.com/SeaQL/sea-orm/pull/1730

**Comment by billy1624** [comment]
Another enhancement would be propagating the database connection acquire error message `DbErr::ConnectionAcquire` changed to something like `DbErr::ConnectionAcquire(FailedToAcquireReason)` or `DbErr::ConnectionAcquire(String)`
