### ISSUE TITLE
Auto derive Linked and/or Related traits impls

### ISSUE THREAD

**Issue by nappa85** [SeaQL/sea-orm#155]
Hello guy,
I was looking at expanded code from `DeriveRelation` proc macro
```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
    )]
    User,
}
```
this code correctly generates `RelationTrait` impl for `Relation`, but not `Linked` or `Related` traits impls, as I expected.

Am I expecting wrong?

**Comment by billy1624** [comment]
Yes, this is the intended behaviour

**Comment by tyt2y3** [comment]
Think of it this way, multiple `Relation` form a `Link`

**Comment by nappa85** [comment]
Ok, thank you very much, because I still haven't clear how two or more link to the same linked entity can coexist

**Comment by tyt2y3** [comment]
Definition

https://github.com/SeaQL/sea-orm/blob/889e9df923a10207f2e9a931716615e739cdaca8/src/tests_cfg/cake.rs#L35-L48

Usage

https://github.com/SeaQL/sea-orm/blob/889e9df923a10207f2e9a931716615e739cdaca8/src/query/join.rs#L262-L274

It's very similar to Relation otherwise, but allows more than 2 joins and several relations between same types.
