### ISSUE TITLE
Implement `CursorTrait` for `SelectTwo`

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#1805]
After a discussion we concluded that cursor-based pagination can be safely implemented for `SelectTwo`. Most of the effort would be in writing tests.

PR is welcomed.

**Comment by ProbablyClem** [comment]
Hey, 
Should the `cursor_by` be appliable on columns from the second table ?
If not, it seems really easy to do as we just need to implement the trait.
Otherwise, we might need a full rework of the cursor.

Maybe we should just implement the `CursorTrait` with support for the first table as a first step, as it seems to me to be the principal use case.

It would also be trivial to add it to `SelectTwoMany` and the incomming [SelectBoth](https://github.com/SeaQL/sea-orm/pull/1633)

What are your thoughts on this ?

**Comment by tyt2y3** [comment]
I think it can be applied to both tables.

**Comment by darkmmon** [comment]
I believe the issue for `SelectTwo` is that we cannot determine which table the `order_column` belongs to.
`cursor_by` only require `IntoIdentity`, therefore we can only get the identity of the column, but not the table it belongs to.
We need ColumnTrait to get the table name, but then we cannot do cursor_by on composite keys.
