### ISSUE TITLE
Change the behavior of update() to return error when rows_affected is 0

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#181]
`update()` can be used with filters. One might, for example, update a record but only if some column of itself still has some value set.

example:

```rust
MyEntity::update(ActiveRecord {
    id: Set(5),
    status: Set("ACTIVE"),
})
.filter(column::Status.eq("READY_FOR_ACTIVATION")
.exec(&db)
.await
```

This is useful to handle idempotency problems: I want to update status but only if, in the meantime, it hasn't yet been updated by another oprocess or something similar.

In this situation (or if I provide an id which does not exist) I have to know if my update has occurred successfully.

One can arg that I could use update_many, but using update gives me the advantage to have the active model itself be returned, which as far as I understand is not the case with update_many.

_Originally posted by @marlon-sousa in https://github.com/SeaQL/sea-orm/discussions/127#discussioncomment-1358559_

We should add a new Error variant, perhaps `RecordNotFound`

**Comment by nicoulaj** [comment]
Alternative API proposition: `ActiveValue` could optionally contain the previous value so that it looks like this:
```
MyEntity::update(ActiveRecord {
    id: Set(5),
    status: Change("READY_FOR_ACTIVATION", "ACTIVE"),
})
.exec(&db)
.await
```

**Comment by Acidic9** [comment]
> Alternative API proposition: ActiveValue could optionally contain the previous value

This seems a little like too much sugar. I personally think it's much more understandable and dynamic if we keep it more simple with just `.filter` instead.

**Comment by marlon-sousa** [comment]
Filter is intuitive enough that must part of people will just understand it out of the box, which should be the ultimate goal of any ORM anyways.

In my way of thinking the less api's you have supporting the most functionality you can the better it is, so that an update process needs:

1. Specify columns to be updated. (ActiveModel)
2. Specify conditions that will make this update request applicable to rows. (filter and similar conditioning buildings)
3. Return a report saying if updates were performed or not, alternatively returning the updated records as to save database hits. (in case of update() which implies that one and only one record should be updated, the updated record or an error if none or more than one records were updated, in the case of update_many a result struct containing the number of affected rows and an optional vector of activeRecords with updated records (full or partial, depending on returning sql clause).
