### ISSUE TITLE
Create SQLite database file

### ISSUE THREAD

**Issue by Stefan99353** [SeaQL/sea-orm#281]
SQLx does have the option to create the database file if it does not exist.
Diesel automatically creates the file by default.

I haven't found any way to do this using sea-orm.

**Comment by billy1624** [comment]
Hey @Stefan99353, you can do it via [from_sqlx_sqlite_pool](https://docs.rs/sea-orm/0.3.1/sea_orm/struct.SqlxSqliteConnector.html#method.from_sqlx_sqlite_pool). Basically you create a ordinary SQLx SQLIte connection then convert it into `sea_orm::DatabaseConnection`.

**Comment by Stefan99353** [comment]
Thanks, that works.
Is there a way to do it in a way to be database agnostic?

**Comment by aaronleopold** [comment]
One thing I've been doing is just appending the appropriate permission flags to the end of the path to the database file in the `Database::connect` call. Since it uses sqlx internally i figured it would work and it seems to have done the trick. For example:

```rust
let connection = Database::connect("/Users/me/.myapp/data.db?mode=rwc").await?;
```

Just make sure the path to wherever you are creating the file exists beforehand (or create it using `std::fs`)

**Comment by tyt2y3** [comment]
Thank you @aaronleopold for helping out!
