### ISSUE TITLE
orm-cli generated incorrect type for #[sea_orm(primary_key)]. Should be u64. Was i64.

### ISSUE THREAD

**Issue by exzachlyvv** [SeaQL/sea-orm#295]
It appears that orm-cli failed to handle unsigned type as a primary key when generating models.

This later resulted in a:

```
panicked at 'Failed to fetch user.: Query("error occurred while decoding column \"id\": mismatched types; Rust type `core::option::Option<i64>` (as SQL type `BIGINT`) is not compatible with SQL type `BIGINT UNSIGNED`")'
```

**Comment by billy1624** [comment]
Hi @exzachlyvv, are you using MySQL?

**Comment by exzachlyvv** [comment]
Yep, MySQL

**Comment by billy1624** [comment]
Currently, we did not capture `UNSIGNED` flag inside `sea-schema` hence `sea-orm-codegen` fail to annotate the column as `u64`.

I guess unsigned integer type is not included in `sea-query` because not all database drivers support it? @tyt2y3 
https://github.com/SeaQL/sea-query/blob/e05a85196fdba9b838b4fb5b62970c783d9c604d/src/table/column.rs#L12-L39

**Comment by tyt2y3** [comment]
Yes, you are right. I checked, SeaSchema does parsed the unsigned flag.

```rust
col_type: SmallInt(
    NumericAttr {
        maximum: None,
        decimal: None,
        unsigned: Some(
            true,
        ),
        zero_fill: None,
    },
)
```

But yeah we have to add it to SeaQuery first before it could be supported. The implication is though, it will not be portable as Postgres does not support unsigned apparently.
