### ISSUE TITLE
Some Questions about comparing with Diesel

### ISSUE THREAD

**Issue by SKTT1Ryze** [SeaQL/sea-orm#308]
Hi : ). 
I'm writing Rust code in a company, and our Rust project is using **diesel** as ORM framework.  
It seems that you are writing another ORM using Rust -- **SeaOrm**, that's amazing!  
Due to many problems on diesel, I consider replacing it with SeaOrm. So I come to you to ask some questions:  
+ SeaOrm supports async, does this feature makes SeaOrm faster than diesel?
+ diesel brings too many binary size, will we get lighter package size with SeaOrm than diesel?
+ Is SeaOrm as safe as diesel?
+ Is SeaOrm supports Sqlite FTS5?

Thanks for your patience!

**Comment by billy1624** [comment]
CC @weiznich

**Comment by weiznich** [comment]
@billy1624 Thanks for the ping :heart:

> Due to many problems on diesel, I consider replacing it with SeaOrm.

As a diesel maintainer I'm always interested in reports on potential problems. May I ask you to open a discussion thread in diesels github repository for this?

Let me provide some answers to some of the questions out of my perspective as diesel maintainer:

> SeaOrm supports async, does this feature makes SeaOrm faster than diesel?

Generally speaking there is no inherent reason why an async or sync API should be slower or faster than the corresponding counter part. There are certain workloads, like a high number of "slow" network requests where an async API **can** offer advantages in terms of throughput and latency, while it may result in more complex and harder to write/understand code.  The classical example there is a web server than needs to accept thousands of concurrent requests per second. Now let's consider a async database library in that context. In my opinion it does not make things that much better, as you still can only execute one query at one point in time per database connection. Postgres for example recommends that you less than 100 concurrent database connections per server. This means async database connection or not you are back beeing able to only process ~100 concurrent requests at a time. Now you can workaround that a bit by using a async database pool which just waits till another connection is available, but that's something you can do independently of if the underlying database library is async or not. If you don't expect that level of traffic the performance side of things is likely irrelevant at all for you. That all written I've written a few benchmarks that run more or less continuously over there in the [diesel repository](https://github.com/diesel-rs/metrics/) to compare the performance of various database connection implementations in rusts ecosystem. Please keep in mind that this is in no way a complete or absolute result there, just that what the underlying code produces (which may or may not fit your usecase.) As always with benchmarks when you are sensitive to performance: Do your own. Measure your own usecase, do not trust other peoples numbers. 

> diesel brings too many binary size, will we get lighter package size with SeaOrm than diesel?

That's a really hard question to answer as it depends on a number of factors. At least I as diesel maintainer would be interested in which sizes you observer and why you believe this size is caused by diesel.

On the one hand a minimal project depending on diesel has only 7 dependencies (including 5 build dependencies) , while a minimal project depending on `sea-orm` has 73 dependencies (again some of them are build dependencies). That by itself does not necessarily mean much, as a single dependency could be really small or really large. Additionally diesel may depend on a native c library to connect to the database. This hides some of the size cost. That's about the size of the libraries itself, but there may also be a size cost in using these crates in your code. The following is blind guessing without having done some numbers there. Diesel code should mostly compile down to nothing/your query string, so there shouldn't be much cost there. I think sea-orm is mostly calling library functions so it should be only a fixed size cost. I would definitively be interested in seeing a few more grounded numbers here.

I cannot comment on the last two questions.

**Comment by tyt2y3** [comment]
For the first two questions, it has to be measured against your particular application.

Some general comments: SeaORM builds query at runtime. This does come at a cost, but for an IO bound workload, the overhead should not bother you too much.

> Is SeaOrm as safe as diesel?

Depends on how you define 'safe'. SeaORM and SQLx has no `unsafe` code, so we are 'safe' for it's meaning in Rust. But SeaORM does not currently have as much compile-time type checking as Diesel, so it's possible that the query you wrote fails at runtime.

> Is SeaOrm supports Sqlite FTS5?

No explicit support is being made.

**Comment by SKTT1Ryze** [comment]
@weiznich 
Thanks for your answers and hard work!  
> As a diesel maintainer I'm always interested in reports on potential problems. May I ask you to open a discussion thread in diesels github repository for this?

Of course you may. I would like to do that.  
> Now you can workaround that a bit by using a async database pool which just waits till another connection is available, but that's something you can do independently of if the underlying database library is async or not. 

This statement completely solved my doubts, pretty professional answer.  

> That's a really hard question to answer as it depends on a number of factors. At least I as diesel maintainer would be interested in which sizes you observer and why you believe this size is caused by diesel.

The sizes that I mainly concern is the binary sizes of  compiled product, possibly caused by generic expansion and macros.  
That is also the main problem which I talk about the DIesel, maybe all the ORM framework. I would open a new issue under Diesel repo and we can discuss this problem on that issue.  

@tyt2y3 Also thanks for your patience!  
> Some general comments: SeaORM builds query (only) at runtime. This does come at a cost, but for an IO bound workload, the overhead should not bother you too much.

The binary size what I concern is not brought by query, but the binary sizes of compiled product.  

> Depends on how you define 'safe'. SeaORM and SQLx has no unsafe code, so we are 'safe' for it's meaning in Rust. But SeaORM does not currently have as much compile-time type checking as Diesel, so it's possible that the query you wrote fails at runtime.

The 'safe' what I mainly mean is whether SeaOrm can prevent [SQL injection](https://en.wikipedia.org/wiki/SQL_injection). Also thanks for your answer.  

> But SeaORM does not currently have as much compile-time type checking as Diesel, so it's possible that the query you wrote fails at runtime.

May this feature bing smaller binary sizes of compiled product? In my opinion，lack of compile-time type check mean lack of much generic code, which bings large binary sizes.  

Finally thanks for your patience! @weiznich @tyt2y3   
I will close this issue next week.

**Comment by tyt2y3** [comment]
If you are concerning SQL injection, then yes, only prepared statements are used in SeaORM. Also, SeaQuery escapes everything including SQL identifiers. Though, if you found a vulnerability, we should discuss privately.

> The binary size what I concern is not brought by query, but the binary sizes of compiled product.

I honestly don't know much about size optimization in Rust. Is there any resources I read from? May be I am able to borrow some techniques and make relevant comments.

**Comment by SKTT1Ryze** [comment]
> If you are concerning SQL injection, then yes, only prepared statements are used in SeaORM. Also, SeaQuery escapes everything including SQL identifiers. Though, if you found a vulnerability, we should discuss privately.
> 
> > The binary size what I concern is not brought by query, but the binary sizes of compiled product.
> 
> I honestly don't know much about size optimization in Rust. Is there any resources I can read? May be I am able to borrow some techniques and make relevant comments.

There' s one post on reddit: https://www.reddit.com/r/rust/comments/otam71/question_about_rusts_binary_size/. 
And in diesel' s case, I guess diesel write too much generic code(I don't mean diesel shouldn't), which may cause large binary size.

**Comment by SKTT1Ryze** [comment]
@weiznich
