### ISSUE TITLE
Chore: test cases for sea-orm-macros

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/sea-orm#504]
thanks for the catch! @billy1624 I imagine we can also add some test cases using the MockInterface?

_Originally posted by @tyt2y3 in https://github.com/SeaQL/sea-orm/issues/494#issuecomment-1025049430_

**Comment by sbshah97** [comment]
Hey I'd love to try this out, i am new to the project but would love the learning.

**Comment by billy1624** [comment]
Hey @sbshah97, happy new year! Sorry for the delay. Do you have anything implementation plan in mind that you want to share? We better have a clear and workable testing plan before coding.

**Comment by sbshah97** [comment]
I don't think I have any clear plan. I'd love to play with the code and get it up first. I plan to run through the code using the CONTRIBUTING guide and set the repo up on my local system. Do you have any additional pointers apart from the Getting Started guide? 

Also any pointers on how I can call this particular code path ?

**Comment by JonasCir** [comment]
Is this ticket about asserting that the generated code by a macro matches the expected value?

**Comment by billy1624** [comment]
This ticket want to test the expected behaviour of `FromQueryResult::from_query_result()` via mock test. From that we can assert the implementation of `FromQueryResult` derive macro is sounded.

A example mock test:

https://github.com/SeaQL/sea-orm/blob/d80e61ed7e2991702a4fc5e95f105ffc16ea609c/src/executor/update.rs#L160-L278
