### ISSUE TITLE
sea-orm-cli generate entity from sqlite generates String for boolean fields

### ISSUE THREAD

**Issue by AngelOnFira** [SeaQL/sea-orm#506]
I haven't gotten to the bottom of diagnosing yet, but I have a table that has a boolean field, in an sqlite database. I'm trying to import the schema from it, but codegen is setting it to a String. Here is what the table looks like:

![image](https://user-images.githubusercontent.com/14791619/152718774-ca8750df-0da1-484e-9ab2-cb134ea7641b.png)

I debugged the schema from [this line](https://github.com/SeaQL/sea-orm/blob/99f55dc194bfed8461675a56840781f38e5cf7b7/sea-orm-cli/src/main.rs#L137), and got this:

![image](https://user-images.githubusercontent.com/14791619/152718881-a0eb0818-c7e2-4731-95b8-830a2f408c79.png)

And the final output is as follows:

```rust
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Custom(\"BLOB\".to_owned())")]
    pub completed: String,
    pub payload: String,
}
```

Is this expected output? I haven't tested on Postgres to see if it's different or anything.

**Comment by billy1624** [comment]
Hey @AngelOnFira, could you also attach the SQL of the SQLite table? Thanks!

**Comment by Hirtol** [comment]
If the datatype displayed in your screenshot is correct then you've got the wrong type. 

It should be a `boolean` instead of a `bool`. Sea-schema parses the types [here](https://github.com/SeaQL/sea-schema/blob/e099830418c207021f96b9842284491c40bf7e24/src/sqlite/types.rs#L72).

`bool` would then be parsed as a `BLOB` instead in your case. (Though `BLOB` has also got the wrong type at the moment, but that is a separate issue)

**Comment by billy1624** [comment]
Nice observations! @Hirtol 
Thanks!!

**Comment by billy1624** [comment]
Hey @AngelOnFira, I will close this for now. If you still have problem on this please reopen it :)
