### ISSUE TITLE
Add flag to sea-orm-cli to generate code for time crate

### ISSUE THREAD

**Issue by cemoktra** [SeaQL/sea-orm#661]
## Summary

Since the `time` crate is supported as alternative to `chrono` it should be possible to generate code for `time` crate

## Motivation

Currently you need to write the ORM code yourself if you want to use the `time` crate, which might be annoying

**Comment by nahuakang** [comment]
I'm looking for a `good first issue` :) Just wondering how one is generating code for `chrono` right now?

**Comment by billy1624** [comment]
Hey @nahuakang, welcome! You can take a look at
- https://github.com/SeaQL/sea-orm/blob/86e7e808b37179315a1cc5c6c852764830c04661/sea-orm-codegen/src/entity/column.rs#L47-L51

**Comment by nahuakang** [comment]
@billy1624 Thanks! I'm reading the docs as well as trying to understand the workflow with `sea-orm` now. Are there any examples/tests that demonstrate how to use `sea-orm-cli` to generate code for entities involving `chrono`? I haven't seen a `chrono` flag in `sea-orm-cli` so I wonder if the solution here is to add a flag for `time` crate or something else (like handling `time` types)?

**Comment by billy1624** [comment]
Hey @nahuakang, you can simply create a database table with timestamp / datetime columns. Then, follow the steps on https://www.sea-ql.org/SeaORM/docs/generate-entity/sea-orm-cli, to generate  entity files with `sea-orm-cli`.

We don't have a `chrono` flag for `sea-orm-cli`, since it's the default crate to represent datetime crate as of now. I think we can add an option, `--date-time-crate`, to `sea-orm-cli generate entity`. It will take values such as `chrono` / `time` with `chrono` being the default. This way it's backward compatible and users can opt-in to it.

**Comment by nahuakang** [comment]
Thanks! I'll give this a try :) Please assign the issue to me.
